export const MNIST_Z2_SINGLE_UPDATE='MNIST_Z2_SINGLE_UPDATE';
export const MNIST_Z4_SINGLE_UPDATE='MNIST_Z4_SINGLE_UPDATE';
export const MNIST_Z4_GRID_UPDATE='MNIST_Z4_GRID_UPDATE';
export const FASHION_Z2_SINGLE_UPDATE='FASHION_Z2_SINGLE_UPDATE';
export const FASHION_Z4_SINGLE_UPDATE='FASHION_Z4_SINGLE_UPDATE';
export const FASHION_Z4_GRID_UPDATE='FASHION_Z4_GRID_UPDATE';
export const NO_ACTION='NO_ACTION';

