export const MNIST_SAMPLE_Z2_UPDATE='MNIST_SAMPLE_Z2_UPDATE';
export const MNIST_SAMPLE_Z4_UPDATE='MNIST_SAMPLE_Z4_UPDATE';
export const FASHION_SAMPLE_Z2_UPDATE='FASHION_SAMPLE_Z2_UPDATE';
export const FASHION_SAMPLE_Z4_UPDATE='FASHION_SAMPLE_Z4_UPDATE';
export const NO_ACTION='NO_ACTION';

